version: "3.8"
services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  db:
    container_name: dockerdev-db
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'automation'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'automation'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  cache:
    driver: local