### Create account request
POST http://localhost:9000/auth/register
Content-Type: application/json
Accept-Language: fa

{
  "confirm_password": "helloworld",
  "password": "helloworld",
  "last_name": "Alizadeh",
  "first_name": "Abolfazl",
  "username": "abolfazlalz"
}

### Login request
POST http://localhost:9000/auth/login
Content-Type: application/json
Accept-Language: fa

{
  "username": "abolfazlalz",
  "password": "helloworld"
}

### User info request
GET http://localhost:9000/auth
Content-Type: application/json
Accept-Language: fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFib2xmYXpsYWx6IiwiZXhwIjoxNjg0MDU5OTE5fQ.z6FExhYs3ABLYh08lyWjxBm1wk0_9CP6Vdydsgdq9H8
